apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db-service.yaml
  - db-deployment.yaml

secretGenerator:
  - name: db-secret
    literals:
      - port=5432
      - password=mypass